### ISSUE TITLE
DoSFilter leaks USER_AUTH entries

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.project#1256]
`DoSFilter` automatically removes `RateTracker` entries that belong to type `USER_IP` or `USER_SESSION`, but not the other types.

`DoSFilter` also needs a code review because for example exposes `RateTracker` as a return type of a public method, but `RateTracker` is package private and so it's not possible to override the method.

**Comment by gregw** [comment]
6 year and counting! We should make this a priority once jetty 12 is released
