### ISSUE TITLE
Explore HTTP/2 Push support based on Link header

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.project#193]
migrated from Bugzilla [#463457](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463457)
status ASSIGNED severity _enhancement_ in component _http2_ for _9.3.x_
Reported in version _9.3.0_ on platform _All_
Assigned to: Simone Bordet

On 2015-03-30 09:21:56 -0400, Simone Bordet wrote:

> https://nghttp2.org/blog/2015/02/10/nghttp2-dot-org-enabled-http2-server-push/

On 2015-03-31 09:42:03 -0400, Simone Bordet wrote:

> See also: https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05690.html

**Comment by sbordet** [comment]
See also: https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/

The idea is that the application adds the `Link` headers and the server, when processing the response, reads those headers to actually perform pushes before the response content is sent.

**Comment by sbordet** [comment]
Follow up: https://blog.cloudflare.com/http-2-server-push-with-multiple-assets-per-link-header/

**Comment by sbordet** [comment]
This would still be nice to have.

**Comment by Kongpcmail** [comment]
> migrated from Bugzilla [#463457](https://bugs.eclipse.org/bugs/show_bug.cgi?id=463457) status ASSIGNED severity _enhancement_ in component _http2_ for _9.3.x_ Reported in version _9.3.0_ on platform _All_ Assigned to: Simone Bordet
> 
> On 2015-03-30 09:21:56 -0400, Simone Bordet wrote:
> 
> > https://nghttp2.org/blog/2015/02/10/nghttp2-dot-org-enabled-http2-server-push/
> 
> On 2015-03-31 09:42:03 -0400, Simone Bordet wrote:
> 
> > See also: https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05690.html

**Comment by joakime** [comment]
Browsers are removing HTTP/2 push support.

* https://developer.chrome.com/blog/removing-push/

With HTTP/3, server push isn't even a thing.

**Comment by joakime** [comment]
Other open source projects have moved to using client side behaviors related to `<link rel="preload">`.
Some area also adopting HTTP Early Hints - ([RFC 8972](https://www.rfc-editor.org/rfc/rfc8297))

* https://twitter.com/dunglas/status/1326552735404060672

**Comment by sbordet** [comment]
As HTTP/2/3 push has been obsoleted, and we have implemented Early Hints, this issue can be closed.
