### ISSUE TITLE
Handle certificates with passwords

### ISSUE THREAD

**Issue by jmcc0nn3ll** [jetty/jetty.project#211]
migrated from Bugzilla [#469579](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469579)
status ASSIGNED severity _normal_ in component _server_ for _9.3.x_
Reported in version _9.3.0_ on platform _PC_
Assigned to: Greg Wilkins

On 2015-06-07 23:41:27 -0400, Greg Wilkins wrote:

> IF a certificate in a keystore has a password that is different from the keystore password, ignore it more elegantly than throwing an exception.   Would also be good to provide and abstract mechanism to allow per key credentials to be set.

**Comment by sbordet** [comment]
Lowering priority.
