### ISSUE TITLE
Review mechanism to scan jars from class-path and module-path

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.project#2988]
In Jetty 10, jar scanning is done in `MetaInfConfiguration` and tested in `MetaInfConfigurationTest`.

We need to review the logic that finds the jars to scan, depending on whether we run Jetty from the class-path or the module-path.

To complicate matters, the Maven Surefire Plugin will always run the tests from the module-path if a `module-info.java` is present.
This makes difficult to add a path to the module-path to verify that jars are indeed picked up from the module-path.

We also need a way to figure out that we are not running from the module-path (perhaps using the Module API) and skip the search on the module-path.

Perhaps we also need a way to force to _not_ look at the module-path, or to force to not look at the class-path, different from what we have now, which is based on Java platform numbers.

**Comment by sbordet** [comment]
See also #3321.

**Comment by olamy** [comment]
give it a bit of time
