### ISSUE TITLE
Make LifeCycle implement AutoCloseable

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.project#3184]
It is so handy in tests to be able to create a `LifeCycle` in a test method and use it with try-with-resources.

```java
public interface LifeCycle extends AutoCloseable
{
    ...
    @Override
    public default void close() throws Exception
    {
        stop();
    }
}
```

Thoughts?

**Comment by gregw** [comment]
We certainly can do:
```java
public interface LifeCycle
{
    ...
    interface Closeable extends LifeCycle, AutoCloseable
    {
        @Override
        default void close() throws Exception
        {
            stop();
        }
    }
}
```

Not sure about making all LifeCycles autocloseable

**Comment by sbordet** [comment]
@gregw

I agree that making all `LifeCycle` also `AutoCloseable` may be a bit too much, although all `LifeCycle` have already a `stop()` method so they kind of are already stoppable/closeable.

 I think introducing `LifeCycle.AutoCloseable` is a bit of duplication, since components can just implement directly `AutoCloseable` directly and just implement `close()` as a one-liner calling `stop()`.
