### ISSUE TITLE
Add hint for setKeyManagerPassword referred during SSL configuration

### ISSUE THREAD

**Issue by digicos** [jetty/jetty.project#3371]
I'd like to point out a minor change that can be incorporated under the heading

> Configuring the Jetty SslContextFactory

on this [page](https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html#loading-keys-and-certificates). Clarification about setKeyManagerPassword from [JavaDocs](https://www.eclipse.org/jetty/javadoc/9.4.14.v20181114/org/eclipse/jetty/util/ssl/SslContextFactory.html#setKeyManagerPassword-java.lang.String-) can be helpful. 
I found it hard to understand what KeyManagerPassword actually meant when I first hit upon the article to configure SSL. The JavaDoc clearly stated that its 

>  The password (if any) for the specific key within the key store. If null is passed and the system property is set, then the getPassword(String) is used to obtain a password from the system property.

**Comment by sbordet** [comment]
@digicos care to prepare a PR for the documentation improvements?
