### ISSUE TITLE
WebAppClassLoader does not define Package

### ISSUE THREAD

**Issue by gregw** [jetty/jetty.project#3487]
The WebAppClassLoader never defines a Package for classes it loads, so that getPackage called on a class loaded in the WebApp will see the package of the same class (but potentially different version) loaded by the container.

**Comment by gregw** [comment]
I have added test to show this problem to jetty-9.3.x with ed03682
I tried to merge through to 9.4.x, but the maven enforcer get's upset about the old version number. @olamy @joakime can you work out how to work around the enforcer for this test - it is a valuable addition going forward that we can load old version of jetty jars in a newer server.

**Comment by gregw** [comment]
Some background on definePackage: 
 * https://stackoverflow.com/questions/12036850/classloader-definepackage-example
 * https://www.javaworld.com/article/2076054/create-a-custom-java-1-2-style-classloader.html

This is all very ancient! 

@sbordet can you think of anything from JPMS we need to consider if we start defining packages ourselves?

**Comment by gregw** [comment]
Note also that we mostly defer to our parent URLClassLoader to defineClasses, however that makes the assumption that it can always delegate to a parent classloader.  This assumption does not hold for webapp classloader as it can invert the precedence so webapp classes can override some system classes.

**Comment by gregw** [comment]
Actually I'm not sure how we can implement this with the inverted classloader mechanism.  The implementation of `Class.getPackage()` just calls `Package.getPackage(Class)` which is implemented as follows:
```java
  static Package getPackage(Class<?> clazz) {
    String name = clazz.getName();
    int dot = name.lastIndexOf('.');
    if (dot != -1) {
      name = name.substring(0, dot);
      ClassLoader loader = clazz.getClassLoader();
      return loader != null ? loader.getPackage(name) : getSystemPackage(name);
    } else {
      return null;
    }
  }
```

So ultimately the classloader is called with just a package name.  But classes from the same package can actually be loaded from either webapp or server classloader, as we have fine grained control over that.   Thus a given classloader can't know what class the package is for, and thus can't tell which package?

**Comment by gregw** [comment]
The problem of defined packages appears to be resolved in java9!

**Comment by gregw** [comment]
The test works fine in java9 and java11 on jetty-9.4, but fails with same JVMs on jetty-10?  So re-opening for more analysis

**Comment by gregw** [comment]
In jetty-10, the test in `tests/test-webapps/test-servlet-spec/test-spec-webapp` works if that webapp is run with `mvn jetty:run`, but fails when that webapp is deployed in a jetty distribution? @sbordet maybe some JPMS difference?

**Comment by joakime** [comment]
Be aware of #1068 and the bugs with `package` discovered in Java 8.

**Comment by joakime** [comment]
> Edit: Dang! I just did a clean build in jetty-10 and now the test is working.

That can be entirely explained by the bad dependency convergence that now exists due to your commit ed036820712c9df14e8fab78ee894974c6583764
(The jetty-util that's used is now a luck of the draw)
I'll work on moving that test (for works with old jetty-util) to a isolated / pre-built war that isn't involved in the dependency tree of the jetty.project maven reactor.
Also, that old jetty-util shouldn't be part of our demo-base either (see https://github.com/eclipse/jetty.project/pull/3942#discussion_r311391196)

**Comment by sbordet** [comment]
@gregw can you seal this one?

**Comment by gregw** [comment]
@sbordet seal?

But I think we can close.

**Comment by gregw** [comment]
check #1068

**Comment by sbordet** [comment]
Is this related to #1068.

**Comment by gregw** [comment]
either we do this for 12.1.0 or we close
