### ISSUE TITLE
HttpClient should handle multiple sessions against the same web app

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.project#799]
See discussion on #75.

**Comment by janbartel** [comment]
@sbordet is this still a live issue?

**Comment by sbordet** [comment]
@janbartel yes, it's a feature request to be able to handle multiple users from a single `HttpClient`, rather than using multiple `HttpClient` instances.

**Comment by joakime** [comment]
@sbordet there's also been a call to have that "multiple authenticated users" also have the ability to use the existing client certificate features in SslContextFactory.

**Comment by sbordet** [comment]
@joakime where is that ?

**Comment by sbordet** [comment]
Closing, as this is a hard issue to solve with one `HttpClient` only; best solution is to use different `HttpClient` instances.

The first problem is to partition connections; that could be achieved with a request tag.

The second problem is to partition cookies; for the same URI, two different users got two different cookies, and they cannot be mixed. In the browser analogy, there would be two browsers, so two `HttpClient`s.

The third problem is to partition authentication credentials/headers; for the same URI, how could `HttpClient` send the Basic username/password of user1, and not that of user2?

Even if 2nd and 3rd problem can be solved via overridable methods, then:
The fourth problem is that there are internal requests made for authentication/redirects/tunnelling that would need to be partitioned in the same way.

All in all, the amount of work necessary to make this work with 1 `HttpClient`, and the security implications if we get it wrong, are not worth the effort.

Using multiple `HttpClient` instances would be the way to go, and if necessary heavyweight components such as the thread pool, the selector manager, the scheduler, etc. can be shared to save memory.
