### ISSUE TITLE
Implement a utility class to save large downloads to a file

### ISSUE THREAD

**Issue by sbordet** [jetty/jetty.project#929]
`HttpClient` could benefit of a utility class that saves the download bytes to a file, akin to:

```
curl <url> -o file.bin
```

Perhaps call it `PathResponseListener`.

Beware that `FileChannel.write(ByteBuffer)` returns the number of bytes written, that can be less than the bytes in the buffer, see also #630.

**Comment by sbordet** [comment]
Would still be nice to have.

**Comment by sbordet** [comment]
@arsenalzp are you interested in implementing this one?

**Comment by arsenalzp** [comment]
> @arsenalzp are you interested in implementing this one?

Hello,
Let's manage with it!

**Comment by sbordet** [comment]
@arsenalzp this is how I would like to use it:

```java
// Async mode.
httpClient.newRequest(host, port)
  .send(new PathResponseListener(Path.of("/tmp/file.bin"));

// CompletableFuture mode.
var request = httpClient.newRequest(host, port);
CompletableFuture<Path> completable = PathResponseListener.write(request, Path.of("/tmp/file.bin"));
```

`PathResponseListener` should implement `CompleteListener` and one of the content listeners, perhaps `ContentListener` is enough.

Start with simple test cases: a test that writes 0 bytes, one that writes 1 MiB and one that writes more than 1 GiB.
Make sure at the end of the test the files are deleted.
Then write test cases for failures: for example a Path that does not exist, a Path that exist but it is not writable, a download that is interrupted by the server (the server writes some content, then closes the connection), etc.

Let me know if you need more guidance.
